### ISSUE TITLE
你好，左右之间的对齐方式要如何设置

### ISSUE THREAD

**Issue by sosoneo** [CharlinFeng/CoreLabel#2]
你好，左右之间的对齐方式要如何设置

**Comment by CharlinFeng** [comment]
@sosoneo  这个，，，，不是普通的UILabel就可以设置嘛

**Comment by sosoneo** [comment]
我又想用富文本 又想水平方向时居中的  所有 我加了这个属性，改变你框架中style的属性
/*\* 左右中的对齐方式 */
@property (nonatomic,assign) NSTextAlignment cl_alignment;

/*\* 左右中的对齐方式 */
-(void)setCl_alignment:(NSTextAlignment)cl_alignment{
    _cl_alignment = cl_alignment;

```
self.style.alignment = _cl_alignment;
```

}

**Comment by sosoneo** [comment]
但我发现这时候垂直方向的对齐方式会失效 － －＃
